#!/usr/bin/env bash
# ============================================================
# Pre-Commit Quality Gate — {{PROJECT_NAME}}
# Stack: {{LANGUAGE}} | Build: {{BUILD_TOOL}} | Runner: {{TEST_RUNNER}}
# Generated by: pre-commit-quality-gate skill
#
# Fail-fast cheap → expensive. Steps 10-14 auto soft-skip without Docker.
#
# SKIP vars (NOT uniform — read carefully):
#   SKIP_SECURITY=1        -> skip step 3  (default: runs)
#   SKIP_RACE=1            -> skip step 9  (default: runs; auto-skips when unsupported)
#   SKIP_INTEGRATION=1     -> skip step 10 (default: runs; auto-skips without Docker)
#   SKIP_MUTATION=1        -> skip step 11 (default: runs; auto-skips without Docker)
#   SKIP_PERF=1            -> skip step 12 (default: runs; auto-skips without Docker)
#   SKIP_SCHEMA=1          -> skip step 13 (default: runs only when schema files staged)
#   SKIP_DOCKER=0          -> ENABLE step 14 (default: OFF — set =0 to run)
#
# Install: git config core.hooksPath .githooks
# ============================================================

set -euo pipefail

# ── Colour helpers ──────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'

step() { echo -e "\n${BOLD}${BLUE}[STEP $1/14] $2${RESET}"; }
pass() { echo -e "${GREEN}[PASS]${RESET} $1"; }
warn() { echo -e "${YELLOW}[WARN]${RESET} $1"; }
fail() { echo -e "${RED}[FAIL]${RESET} $1"; exit 1; }
skip() { echo -e "${YELLOW}[SKIP]${RESET} $1"; }

# ── Infrastructure detection ────────────────────────────────
has_docker()    { docker info &>/dev/null 2>&1; }
# has_cgo()     { {{CGO_CHECK}}; }                        # Go only
# has_registry(){ curl -sf --max-time 3 "$REGISTRY"; }   # for step 14
# has_cloud_creds() { [[ -n "${CLOUD_KEY:-}" ]]; }       # for step 14

# ── Step -1: Secret Scanner (Gitleaks) ──────────────────────
step "-1" "Secret Scanner — Gitleaks"
if command -v gitleaks &> /dev/null; then
  gitleaks protect -v --staged || fail "Gitleaks encontrou segredos/chaves de API! Remova-os antes de commitar."
else
  warn "Gitleaks não instalado. Secret scanning soft-skipped."
fi
pass "Secret Scanner"

# ── Step 0: Git Flow Branch Name ────────────────────────────
step "0" "Branch Name — Validação Git Flow"
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "HEAD")
VALID_BRANCH_REGEX="^(feature|bugfix|hotfix|release|support)\/[a-zA-Z0-9._-]+$|^(main|master|develop)$"
if [[ "$BRANCH_NAME" != "HEAD" ]] && [[ ! "$BRANCH_NAME" =~ $VALID_BRANCH_REGEX ]]; then
  fail "Nome da branch inválido: '$BRANCH_NAME'. Use o padrão Git Flow (feature/..., bugfix/..., hotfix/..., release/..., develop, main)."
fi
pass "Branch Name"

# ── Step 1: Formatter ───────────────────────────────────────
step "1" "{{STEP_1_NAME}} — {{STEP_1_DESC}}"
{{STEP_1_COMMAND}}
pass "{{STEP_1_NAME}}"

# ── Step 2: Linter ──────────────────────────────────────────
step "2" "{{STEP_2_NAME}} — {{STEP_2_DESC}}"
{{STEP_2_COMMAND}}
pass "{{STEP_2_NAME}}"

# ── Step 3: Security scan ───────────────────────────────────
step "3" "{{STEP_3_NAME}} — {{STEP_3_DESC}}"
if [[ "${SKIP_{{3_VAR}}:-0}" == "1" ]]; then
  skip "{{STEP_3_NAME}} (SKIP_{{3_VAR}}=1)"
else
  {{STEP_3_COMMAND}}
  pass "{{STEP_3_NAME}}"
fi

# ── Step 4: Dead code ───────────────────────────────────────
step "4" "{{STEP_4_NAME}} — {{STEP_4_DESC}}"
{{STEP_4_COMMAND}}
pass "{{STEP_4_NAME}}"

# ── Step 5: Modernizer (report-only) ───────────────────────
step "5" "{{STEP_5_NAME}} — {{STEP_5_DESC}}"
{{STEP_5_COMMAND}} || warn "{{STEP_5_NAME}}: idioms modernos disponíveis (non-blocking)"

# ── Step 6: Convention guards ───────────────────────────────
step "6" "Convention guards — {{STEP_6_DESC}}"
{{STEP_6_COMMANDS}}
pass "Convention guards"

# ── Step 7: Module hygiene ──────────────────────────────────
step "7" "{{STEP_7_NAME}} — {{STEP_7_DESC}}"
{{STEP_7_COMMAND}}
pass "{{STEP_7_NAME}}"

# ── Step 8: Tests + coverage ────────────────────────────────
step "8" "{{STEP_8_NAME}} — {{STEP_8_DESC}}"
{{STEP_8_COMMAND}}
{{COVERAGE_THRESHOLD_CHECK}}
pass "{{STEP_8_NAME}}"

# ── Step 9: Race / concurrency detector ─────────────────────
step "9" "{{STEP_9_NAME}} — {{STEP_9_DESC}}"
if [[ "${SKIP_{{9_VAR}}:-0}" == "1" ]]; then
  skip "{{STEP_9_NAME}} (SKIP_{{9_VAR}}=1)"
elif ! {{RACE_PREREQ_CHECK}}; then
  warn "{{STEP_9_NAME}} prerequisite unavailable — soft-skipping"
else
  {{STEP_9_COMMAND}}
  pass "{{STEP_9_NAME}}"
fi

# ── Step 10: Integration tests (WireMock / HTTP mocks) ──────
step "10" "Integration tests — fluxos completos via {{MOCK_TOOL}}"
if [[ "${SKIP_INTEGRATION:-0}" == "1" ]]; then
  skip "Integration tests (SKIP_INTEGRATION=1)"
elif ! has_docker; then
  warn "Docker unavailable — integration tests soft-skipped"
else
  {{STEP_10_SETUP}}
  trap '{{STEP_10_TEARDOWN}}' EXIT
  {{STEP_10_COMMAND}}
  pass "Integration tests"
fi

# ── Step 11: Mutation tests ─────────────────────────────────
step "11" "Mutation tests — qualidade da suíte via {{MUTATION_TOOL}}"
if [[ "${SKIP_MUTATION:-0}" == "1" ]]; then
  skip "Mutation tests (SKIP_MUTATION=1)"
elif ! has_docker; then
  warn "Docker unavailable — mutation tests soft-skipped"
else
  {{STEP_11_COMMAND}}
  {{MUTATION_THRESHOLD_CHECK}}
  pass "Mutation tests"
fi

# ── Step 12: Performance tests ──────────────────────────────
step "12" "Performance tests — latência/throughput via {{PERF_TOOL}}"
if [[ "${SKIP_PERF:-0}" == "1" ]]; then
  skip "Performance tests (SKIP_PERF=1)"
elif ! has_docker; then
  warn "Docker unavailable — performance tests soft-skipped"
else
  {{STEP_12_SETUP}}
  trap '{{STEP_12_TEARDOWN}}' EXIT
  {{STEP_12_COMMAND}}
  pass "Performance tests"
fi

# ── Step 13: Schema pipeline (only when schema files staged) ─
step "13" "{{STEP_13_NAME}} — {{STEP_13_DESC}}"
SCHEMA_STAGED=$(git diff --cached --name-only --diff-filter=ACM \
  | grep -E '{{SCHEMA_FILE_PATTERN}}' || true)

if [[ "${SKIP_SCHEMA:-0}" == "1" ]]; then
  skip "{{STEP_13_NAME}} (SKIP_SCHEMA=1)"
elif [[ -z "$SCHEMA_STAGED" ]]; then
  skip "{{STEP_13_NAME}} — nenhum schema staged"
else
  {{STEP_13_COMMAND}}
  git add .
  pass "{{STEP_13_NAME}}"
fi

# ── Step 14: Production build (OFF by default) ──────────────
step "14" "{{STEP_14_NAME}} — {{STEP_14_DESC}}"
if [[ "${SKIP_DOCKER:-1}" != "0" ]]; then
  skip "{{STEP_14_NAME}} (set SKIP_DOCKER=0 to enable)"
elif ! has_docker; then
  warn "Docker unavailable — {{STEP_14_NAME}} soft-skipped"
elif ! {{CLOUD_CREDS_CHECK}}; then
  warn "Cloud credentials or registry unreachable — {{STEP_14_NAME}} soft-skipped (off VPN?)"
else
  {{STEP_14_COMMAND}}
  pass "{{STEP_14_NAME}}"
fi

echo -e "\n${GREEN}${BOLD}✓ All 14 quality gates passed — committing.${RESET}\n"
